language: node_js
node_js:
  - "stable"
services:
  - postgresql
cache:
  directories:
    - "node_modules"
env:
  global:
    - DB_ENV=testing
   
before_script:
  - psql -c 'create database backend_test;' -U postgres
  - npm install -g nyc


script:
  - nyc --reporter=lcov npm test
  - sudo /etc/init.d/redis-server stop
  - sudo /etc/init.d/postgresql stop 
after_script:
  -  nyc report --reporter=text-lcov | coveralls

notifications:
  email: false
